# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: marcograss' blog
email: marco.gra+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog with some sparse posts about Computer Security, Bugs, Electronics and
  whatelse. Stuff and opinions written here are mine only.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcograss.github.io" # the base hostname & protocol for your site
twitter_username: marcograss
github_username:  marcograss

# Build settings
markdown: kramdown
